apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-k8s
  name: django
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: registry.digitalocean.com/aininjas-docker-registry/aininjas_production_django
        command: ["/start"]
        resources:
          requests:
            cpu: "500m"
            memory: "1000M"
          limits:
            cpu: "500m"
            memory: "1000M"
        envFrom:
        - configMapRef:
            name: django-env
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: Q4bjRxdd503AR40J

        ports:
        - containerPort: 5000
        volumeMounts:
        - name: static-files
          mountPath: /app/static/
      imagePullSecrets:
      - name: registry-aininjas-docker-registry
      volumes:
      - name: static-files
        emptyDir: {}
