kind: Service
apiVersion: v1
metadata:
  namespace: test-k8s
  name: django-service
spec:
  selector:
    pod: django
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
