apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: celeryflower
  namespace: test-k8s
  name: celeryflower  # name should be anything put flower: https://github.com/mher/flower/issues/738
spec:
  replicas: 1
  selector:
    matchLabels:
      service: celeryflower
  template:
    metadata:
      labels:
        service: celeryflower
    spec:
      containers:
      - args:
        - /start-flower
        envFrom:
          - configMapRef:
              name: envs-production-django
          - configMapRef:
              name: envs-production-postgres
          - secretRef:
              name: secrets-production-django
          - secretRef:
              name: secrets-production-postgres
        image: registry.digitalocean.com/aininjas-docker-registry/aininjas_production_test_flower
        env:
          - name: CELERY_BROKER_URL
            value: $(REDIS_URL)
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
        name: celeryflower
        ports:
          - containerPort: 5555
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  name: celeryflower
  namespace: test-k8s
  labels:
    service: celeryflower
spec:
  ports:
  - port: 5555
    targetPort: 5555
    name: http
  selector:
    service: celeryflower
