# Generated by Django 4.1.5 on 2023-03-16 16:37

from django.db import migrations, models
import django_extensions.db.fields
import fernet_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SbPublicUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.TextField(blank=True)),
                ("last_name", models.TextField(blank=True)),
                ("email", models.TextField(blank=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SbUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.TextField(blank=True)),
                ("last_name", models.TextField(blank=True)),
                ("email", models.TextField(blank=True)),
            ],
            options={
                "db_table": "sb_users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SbUserProfile",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.TextField(blank=True)),
                ("last_name", models.TextField(blank=True)),
                ("email", models.CharField(editable=False, max_length=255)),
                ("openai_key", models.CharField(blank=True, max_length=255)),
                ("chatgpt_plus_username", models.CharField(blank=True, max_length=255)),
                (
                    "chatgpt_plus_password",
                    fernet_fields.fields.EncryptedTextField(blank=True),
                ),
            ],
            options={
                "db_table": "sb_users_profile",
            },
        ),
    ]
