# Generated by Django 4.1.5 on 2023-03-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sbusers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sbuserprofile",
            name="created",
        ),
        migrations.RemoveField(
            model_name="sbuserprofile",
            name="modified",
        ),
    ]
