# Generated by Django 4.1.5 on 2023-03-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbusers", "0003_alter_sbuserprofile_chatgpt_plus_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sbuserprofile",
            name="first_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="sbuserprofile",
            name="last_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
