# Generated by Django 4.1.5 on 2023-03-16 18:01

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sbusers", "0004_alter_sbuserprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sbuserprofile",
            name="chatgpt_plus_password",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True, default="", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sbuserprofile",
            name="chatgpt_plus_username",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sbuserprofile",
            name="openai_key",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
