# Generated by Django 4.1.5 on 2023-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbusers", "0005_alter_sbuserprofile_chatgpt_plus_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbuserprofile",
            name="avatar_pic",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sbuserprofile",
            name="username",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
