apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        # image: aininjas_production_django
        image: registry.digitalocean.com/aininjas-docker-registry/django:$DJANGO_IMAGE_TAG

        envFrom:
        - configMapRef:
            name: django-env
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: tmp-files
          mountPath: /tmp
        - name: app-files
          mountPath: /app
      volumes:
      - name: tmp-files
        hostPath:
          path: /home/bryanl/100gbdrive/tmp
      - name: app-files
        hostPath:
          path: /path/to/your/local/app
