apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: aininjas_production_flower
        envFrom:
        - configMapRef:
            name: django-env
        volumeMounts:
        - name: tmp-files
          mountPath: /tmp
        - name: app-files
          mountPath: /app
      volumes:
      - name: tmp-files
        hostPath:
          path: /home/bryanl/100gbdrive/tmp
      - name: app-files
        hostPath:
          path: /path/to/your/local/app
