# Generated by Django 4.1.5 on 2023-03-16 16:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sbusers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCreator",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creator_name", models.CharField(blank=True, max_length=255)),
                ("creator_id", models.CharField(max_length=255, unique=True)),
                ("creator_url", models.CharField(blank=True, max_length=255)),
                ("profile_json_blob", models.JSONField(blank=True, default=dict)),
                (
                    "source_channel",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("TWITTER", "TWITTER"),
                            ("YOUTUBE", "YOUTUBE"),
                        ],
                        default="NONE",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContentProcessed",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number_of_speaker", models.IntegerField(default=1)),
                (
                    "processing_algo_type",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("NORMAL_YT_TRANSCRIBE", "NORMAL_YT_TRANSCRIBE"),
                            ("SPEAKER_TRANSCRIBE", "SPEAKER_TRANSCRIBE"),
                        ],
                        default="NONE",
                        max_length=50,
                    ),
                ),
                (
                    "processed_content_json_blob",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("ERROR", "ERROR"),
                            ("WAV_JOB_STARTED", "WAV_JOB_STARTED"),
                            ("WAV_STORED", "WAV_STORED"),
                            ("TRANSCRIPT_STORED", "TRANSCRIPT_STORED"),
                            ("READY_TO_CHUNK", "READY_TO_CHUNK"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        default="NONE",
                        max_length=255,
                    ),
                ),
                ("state_artifact_blob", models.JSONField(blank=True, default=dict)),
                ("is_chunked", models.BooleanField(default=False)),
                ("output_artifacts_url", models.CharField(blank=True, max_length=255)),
                ("time_to_process", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContentYtChunk",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transcript_start_time", models.IntegerField(default=-1)),
                ("content_chunk_title", models.TextField(blank=True)),
                ("content_chunk_text", models.TextField(blank=True)),
                ("content_segments_json", models.JSONField(blank=True, default=dict)),
                ("raw_data_json_blob", models.JSONField(blank=True, default=dict)),
                (
                    "content_processed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_chunks",
                        to="contents.contentprocessed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("meta_json_blob", models.JSONField(blank=True, default=dict)),
                ("prompt", models.TextField(blank=True)),
                (
                    "prompt_hashed",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "categories",
                    models.CharField(
                        choices=[("NONE", "NONE"), ("SUMMARIZATION", "SUMMARIZATION")],
                        default="NONE",
                        max_length=50,
                    ),
                ),
                (
                    "exec_type",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("DEFAULT", "DEFAULT"),
                            ("YT_FINAL_SUMMARIZE", "YT_FINAL_SUMMARIZE"),
                        ],
                        default="NONE",
                        max_length=50,
                    ),
                ),
                (
                    "sb_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sbusers.sbuserprofile",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromptCompletion",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt_text", models.TextField(blank=True)),
                ("prompt_hashed", models.CharField(blank=True, max_length=255)),
                (
                    "completion_state",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="NONE",
                        max_length=255,
                    ),
                ),
                ("output_completion", models.TextField(blank=True)),
                (
                    "content_chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contents.contentytchunk",
                    ),
                ),
                (
                    "content_processed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contents.contentprocessed",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contents.prompt",
                    ),
                ),
                (
                    "sb_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sbusers.sbuserprofile",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserPromptRunVersion",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("YT_CHUNK_SUMMARIZE", "YT_CHUNK_SUMMARIZE"),
                            ("YT_FINAL_SUMMARIZE", "YT_FINAL_SUMMARIZE"),
                        ],
                        default="NONE",
                        max_length=255,
                    ),
                ),
                (
                    "processed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contents.contentprocessed",
                    ),
                ),
                (
                    "sb_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sbusers.sbuserprofile",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromptCompletionExecutionHistory",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt_completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contents.promptcompletion",
                    ),
                ),
                (
                    "source_content_chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contents.contentytchunk",
                    ),
                ),
                (
                    "source_content_processed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contents.contentprocessed",
                    ),
                ),
                (
                    "user_processed_prompt_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contents.userpromptrunversion",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContentSource",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=255, unique=True)),
                ("content_title", models.CharField(blank=True, max_length=255)),
                ("content_description", models.TextField(blank=True)),
                (
                    "content_categories",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("GPT", "GPT"),
                            ("CRYPTO", "CRYPTO"),
                        ],
                        default="NONE",
                        max_length=50,
                    ),
                ),
                ("raw_content_json_blob", models.JSONField(blank=True, default=dict)),
                ("param_json_blob", models.JSONField(blank=True, default=dict)),
                (
                    "speaker_type",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("MONO", "MONO"),
                            ("DUO", "DUO"),
                            ("MULTI", "MULTI"),
                        ],
                        default="MONO",
                        max_length=50,
                    ),
                ),
                ("number_of_speaker", models.IntegerField(default=1)),
                ("speakers_blob", models.JSONField(blank=True, default=dict)),
                (
                    "content_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contents.contentcreator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contentprocessed",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contents.contentsource"
            ),
        ),
        migrations.AddIndex(
            model_name="contentytchunk",
            index=models.Index(
                fields=["content_processed", "transcript_start_time"],
                name="contents_co_content_7a16e1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentytchunk",
            unique_together={("content_processed", "transcript_start_time")},
        ),
        migrations.AddIndex(
            model_name="contentsource",
            index=models.Index(fields=["url"], name="contents_co_url_1a7cb4_idx"),
        ),
    ]
