# Generated by Django 4.1.5 on 2023-03-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="meta_json_blob",
        ),
    ]
