# Generated by Django 4.1.5 on 2023-03-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0007_update_prompt_exec_type_default_yt_final_summarize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promptcompletion",
            name="is_default",
        ),
        migrations.AddField(
            model_name="prompt",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
