# Generated by Django 4.1.5 on 2023-03-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sbusers", "0006_sbuserprofile_avatar_pic_sbuserprofile_username"),
        ("contents", "0008_remove_promptcompletion_is_default_prompt_is_default"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prompt",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together={("sb_user", "exec_type", "is_default")},
        ),
    ]
