# Generated by Django 4.1.5 on 2023-03-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0009_alter_prompt_options_alter_prompt_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="prompt_hashed",
        ),
    ]
