# Generated by Django 4.1.5 on 2023-03-20 17:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("sbusers", "0006_sbuserprofile_avatar_pic_sbuserprofile_username"),
        ("contents", "0010_remove_prompt_prompt_hashed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prompt",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="is_default",
        ),
        migrations.CreateModel(
            name="UserDefaultPrompt",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exec_type",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("DEFAULT_CHUNK_SUMMARIZE", "DEFAULT_CHUNK_SUMMARIZE"),
                            (
                                "DEFAULT_YT_FINAL_SUMMARIZE",
                                "DEFAULT_YT_FINAL_SUMMARIZE",
                            ),
                        ],
                        default="NONE",
                        max_length=50,
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contents.prompt",
                    ),
                ),
                (
                    "sb_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sbusers.sbuserprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("sb_user", "exec_type")},
            },
        ),
    ]
