# Generated by Django 4.1.5 on 2023-03-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0011_alter_prompt_options_alter_prompt_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdefaultprompt",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contents.prompt",
            ),
        ),
    ]
