# Generated by Django 4.1.5 on 2023-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0012_alter_userdefaultprompt_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsource",
            name="content_meta_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
