apiVersion: v1
kind: Service
metadata:
  namespace: test-k8s
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - port: 5555
      name: flower
    - port: 80
      name: http
    - port: 443
      name: tls
