name: Build and Push Docker Images

on:
  push:
    branches:
      - do-k8s

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DO_API_KEY }}
        password: ${{ secrets.DO_API_KEY }}


    - name: Build and push images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./compose/production/django/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          registry.digitalocean.com/aininjas-docker-registry/aininjas_production_django:latest


# registry.digitalocean.com/aininjas-docker-registry/aininjas_production_celeryworker:latest
          # registry.digitalocean.com/aininjas-docker-registry/aininjas_production_celerybeat:latest
          # registry.digitalocean.com/aininjas-docker-registry/aininjas_production_flower:latest

    # - name: Build and push Docker images from Docker Compose
    #   run: |
    #     docker-compose -f prod.yml build && docker-compose -f prod.yml push

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     file: ./prod.yml
    #     push: true
    #     tags: registry.digitalocean.com/aininjas-docker-registry/your_image_name:latest
